### ISSUE TITLE
Software Information

### ISSUE THREAD

**Issue by croaljack0** [rv456/BowlsEye#2]
Further information on how the software is constructed would be helpful.
This could be a description of the classes, or a UML diagram etc.

** Team 10 **

**Comment by rv456** [comment]
Thank you for highlighting this issue, our final code will be fully documented!

**Comment by rv456** [comment]
We have added documentation for the current raspberry pi codebase [here](https://rv456.github.io/BowlsEye/index.html).  We will continue to update this resource as we finalise the software for both the raspberry pi and the GUI.

Thanks,
- Team 18
