### ISSUE TITLE
 Need more information about the work flow of the whole project.

### ISSUE THREAD

**Issue by JiananKan** [rv456/BowlsEye#3]
To provide some UML graphs maybe a good way to describe.

team 6

**Comment by rv456** [comment]
Thank you for highlighting this issue, we are currently working on code documentation

**Comment by rv456** [comment]
Hi, we have added the current documented code [here](https://rv456.github.io/BowlsEye/index.html) where you can see include dependency and call graphs.  We will continue to maintain this and have also updated the main README to give an overview of the structure of the full repository.

Thanks
- Team 18
