### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by acra6488** [rv456/BowlsEye#4]
Perhaps add a section on problems encountered and solutions that worked (and those that didn't work!)
This can be during the design, fabrication or testing stages.
Some notes and pictures would be great. Maybe linking to a social media page too.
-Aurelie -Team 2

**Comment by rv456** [comment]
Hi, we already have links to social media in our main README.  We have also added readme's for all code examples with build/usage instructions and links to any external libraries used which should help with troubleshooting.  We have also started a [wiki](https://github.com/rv456/BowlsEye/wiki) which will contain the section you ask for on solutions to problems when we solve them!

Thanks
- Team 18
